In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv("C:/Users/Mohan/Documents/candy/data/version_2/candy_data.csv")

In [7]:
df.head()

,Unnamed: 0,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,...,Sales,Units,Gross Profit,Cost,Factory,Unit Price,Unit Cost,Latitude,Longitude,Target
0,0,282,US-2021-128055-CHO-TRI-54000,2021-03-31,2026-09-26,Standard Class,128055,United States,San Francisco,California,...,7.50,2,4.90,2.60,Wicked Choccy's,3.75,1.30,32.076176,-81.088371,27000
1,1,288,US-2021-128055-CHO-SCR-58000,2021-03-31,2026-09-26,Standard Class,128055,United States,San Francisco,California,...,7.20,2,5.00,2.20,Lot's O' Nuts,3.60,1.10,32.881893,-111.768036,27000
2,2,1132,US-2021-138100-CHO-FUD-51000,2021-09-15,2027-03-13,Standard Class,138100,United States,New York City,New York,...,7.20,2,4.80,2.40,Lot's O' Nuts,3.60,1.20,32.881893,-111.768036,27000
3,3,1133,US-2021-138100-CHO-MIL-31000,2021-09-15,2027-03-13,Standard Class,138100,United States,New York City,New York,...,9.75,3,6.33,3.42,Wicked Choccy's,3.25,1.14,32.076176,-81.088371,27000
4,4,3396,US-2022-121391-CHO-MIL-31000,2022-10-04,2028-03-29,First Class,121391,United States,San Francisco,California,...,6.50,2,4.22,2.28,Wicked Choccy's,3.25,1.14,32.076176,-81.088371,27000

In [8]:
df.shape

(10188, 25)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10188 entries, 0 to 10187
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      10188 non-null  int64
 1   Row ID          10188 non-null  int64
 2   Order ID        10188 non-null  str
 3   Order Date      10188 non-null  str
 4   Ship Date       10188 non-null  str
 5   Ship Mode       10188 non-null  str
 6   Customer ID     10188 non-null  int64
 7   Country/Region  10188 non-null  str
 8   City            10188 non-null  str
 9   State/Province  10188 non-null  str
 10  Postal Code     10188 non-null  str
 11  Division        10188 non-null  str
 12  Region          10188 non-null  str
 13  Product ID      10188 non-null  str
 14  Product Name    10188 non-null  str
 15  Sales           10188 non-null  float64
 16  Units           10188 non-null  int64
 17  Gross Profit    10188 non-null  float64
 18  Cost            10188 non-null  float64
 19  Factory         10188 non-null  str
 20  Unit Price      10188 non-null  float64
 21  Unit Cost       10188 non-null  float64
 22  Latitude        10188 non-null  float64
 23  Longitude       10188 non-null  float64
 24  Target          10188 non-null  int64
dtypes: float64(7), int64(5), str(13)
memory usage: 1.9 MB

In [13]:
df = df.loc[:, ~df.columns.str.contains("^Unnamed")]

In [15]:
df["Order Date"]= pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10188 entries, 0 to 10187
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10188 non-null  int64
 1   Order ID        10188 non-null  str
 2   Order Date      10188 non-null  datetime64[us]
 3   Ship Date       10188 non-null  datetime64[us]
 4   Ship Mode       10188 non-null  str
 5   Customer ID     10188 non-null  int64
 6   Country/Region  10188 non-null  str
 7   City            10188 non-null  str
 8   State/Province  10188 non-null  str
 9   Postal Code     10188 non-null  str
 10  Division        10188 non-null  str
 11  Region          10188 non-null  str
 12  Product ID      10188 non-null  str
 13  Product Name    10188 non-null  str
 14  Sales           10188 non-null  float64
 15  Units           10188 non-null  int64
 16  Gross Profit    10188 non-null  float64
 17  Cost            10188 non-null  float64
 18  Factory         10188 non-null  str
 19  Unit Price      10188 non-null  float64
 20  Unit Cost       10188 non-null  float64
 21  Latitude        10188 non-null  float64
 22  Longitude       10188 non-null  float64
 23  Target          10188 non-null  int64
dtypes: datetime64[us](2), float64(7), int64(4), str(11)
memory usage: 1.9 MB

In [18]:
df_numeric = df.select_dtypes(include=['number'])
df_categorical = df.select_dtypes(exclude=['number'])

In [19]:
df_numeric.info()

<class 'pandas.DataFrame'>
RangeIndex: 10188 entries, 0 to 10187
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Row ID        10188 non-null  int64
 1   Customer ID   10188 non-null  int64
 2   Sales         10188 non-null  float64
 3   Units         10188 non-null  int64
 4   Gross Profit  10188 non-null  float64
 5   Cost          10188 non-null  float64
 6   Unit Price    10188 non-null  float64
 7   Unit Cost     10188 non-null  float64
 8   Latitude      10188 non-null  float64
 9   Longitude     10188 non-null  float64
 10  Target        10188 non-null  int64
dtypes: float64(7), int64(4)
memory usage: 875.7 KB

In [21]:
df_numeric.head()

,Row ID,Customer ID,Sales,Units,Gross Profit,Cost,Unit Price,Unit Cost,Latitude,Longitude,Target
0,282,128055,7.50,2,4.90,2.60,3.75,1.30,32.076176,-81.088371,27000
1,288,128055,7.20,2,5.00,2.20,3.60,1.10,32.881893,-111.768036,27000
2,1132,138100,7.20,2,4.80,2.40,3.60,1.20,32.881893,-111.768036,27000
3,1133,138100,9.75,3,6.33,3.42,3.25,1.14,32.076176,-81.088371,27000
4,3396,121391,6.50,2,4.22,2.28,3.25,1.14,32.076176,-81.088371,27000

In [27]:
df_categorical.info()

<class 'pandas.DataFrame'>
RangeIndex: 10188 entries, 0 to 10187
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        10188 non-null  str
 1   Order Date      10188 non-null  datetime64[us]
 2   Ship Date       10188 non-null  datetime64[us]
 3   Ship Mode       10188 non-null  str
 4   Country/Region  10188 non-null  str
 5   City            10188 non-null  str
 6   State/Province  10188 non-null  str
 7   Postal Code     10188 non-null  str
 8   Division        10188 non-null  str
 9   Region          10188 non-null  str
 10  Product ID      10188 non-null  str
 11  Product Name    10188 non-null  str
 12  Factory         10188 non-null  str
dtypes: datetime64[us](2), str(11)
memory usage: 1.0 MB

In [68]:
df["Country/Region"].value_counts()

Country/Region
United States    9988
Canada            200
Name: count, dtype: int64

In [69]:
df["Division"].value_counts()

Division
Chocolate    9844
Other         310
Sugar          34
Name: count, dtype: int64

In [70]:
df["Ship Mode"].value_counts()

Ship Mode
Standard Class    6116
Second Class      1979
First Class       1546
Same Day           547
Name: count, dtype: int64

In [71]:
df["Region"].value_counts()

Region
Pacific     3252
Atlantic    2984
Interior    2333
Gulf        1619
Name: count, dtype: int64

In [72]:
df["Factory"].value_counts()

Factory
Lot's O' Nuts        5692
Wicked Choccy's      4152
Secret Factory        217
The Other Factory     100
Sugar Shack            27
Name: count, dtype: int64

In [73]:
df["Product Name"].value_counts()

Product Name
Wonka Bar - Milk Chocolate           2137
Wonka Bar -Scrumdiddlyumptious       2064
Wonka Bar - Triple Dazzle Caramel    2015
Wonka Bar - Fudge Mallows            1818
Wonka Bar - Nutty Crunch Surprise    1810
Wonka Gum                             120
Kazookles                              96
Lickable Wallpaper                     94
SweeTARTS                              10
Laffy Taffy                            10
Nerds                                   4
Hair Toffee                             4
Everlasting Gobstopper                  3
Fun Dip                                 3
Name: count, dtype: int64

In [74]:
df["State/Province"].value_counts()

State/Province
California                   2001
New York                     1127
Texas                         985
Pennsylvania                  586
Washington                    506
Illinois                      491
Ohio                          469
Florida                       382
Michigan                      254
North Carolina                249
Virginia                      224
Arizona                       223
Georgia                       184
Tennessee                     183
Colorado                      182
Indiana                       149
Kentucky                      139
Massachusetts                 135
New Jersey                    130
Oregon                        124
Wisconsin                     110
Maryland                      105
Delaware                       96
Minnesota                      89
Connecticut                    82
Missouri                       66
Oklahoma                       66
Alabama                        61
Arkansas                       60
Ontario                        58
Rhode Island                   56
Mississippi                    53
Utah                           53
Quebec                         50
Louisiana                      42
South Carolina                 42
Nevada                         39
Nebraska                       38
New Mexico                     37
Iowa                           30
New Hampshire                  27
Alberta                        26
Kansas                         24
British Columbia               22
Idaho                          21
Montana                        15
South Dakota                   12
Manitoba                       12
Vermont                        11
District of Columbia           10
Prince Edward Island           10
Maine                           8
New Brunswick                   8
North Dakota                    7
Newfoundland and Labrador       6
Nova Scotia                     6
West Virginia                   4
Saskatchewan                    2
Wyoming                         1
Name: count, dtype: int64

In [75]:
df["City"].value_counts()

City
New York City    914
Los Angeles      747
Philadelphia     536
San Francisco    510
Seattle          428
                ...
Grand Island       1
Cedar Rapids       1
Ormond Beach       1
San Mateo          1
Portage            1
Name: count, Length: 542, dtype: int64

In [76]:
df["Postal Code"].value_counts()

Postal Code
10035    263
10024    230
10009    229
94122    203
10011    192
        ...
68801      1
52402      1
32174      1
94403      1
46368      1
Name: count, Length: 654, dtype: int64

In [77]:
df_numeric.head()

,Row ID,Customer ID,Sales,Units,Gross Profit,Cost,Unit Price,Unit Cost,Latitude,Longitude,Target
0,282,128055,7.50,2,4.90,2.60,3.75,1.30,32.076176,-81.088371,27000
1,288,128055,7.20,2,5.00,2.20,3.60,1.10,32.881893,-111.768036,27000
2,1132,138100,7.20,2,4.80,2.40,3.60,1.20,32.881893,-111.768036,27000
3,1133,138100,9.75,3,6.33,3.42,3.25,1.14,32.076176,-81.088371,27000
4,3396,121391,6.50,2,4.22,2.28,3.25,1.14,32.076176,-81.088371,27000

In [49]:
print("Total sales ",df["Sales"].sum())

Total sales  141704.88

# Total sales  141704.88$

In [52]:
print("total Profit",df["Gross Profit"].sum())

total Profit 93395.54999999999

# total Profit 93395.54999999999$

In [57]:
profit_margin = (df["Gross Profit"]/df["Sales"])*100
print("profit margin",profit_margin.mean(),"%")

profit margin 66.51788111131033 %

# profit margin 66.51788111131033 %

In [58]:
print("total units sold",df["Units"].sum())

total units sold 38633

# total units sold 38633

In [59]:
print("total orders",df["Order ID"].count())

total orders 10188

# total orders 10188

In [78]:
df["Order Date"].value_counts().mean()

np.float64(8.202898550724637)

# Average Order per day 8(approximately)

In [80]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name',
       'Sales', 'Units', 'Gross Profit', 'Cost', 'Factory', 'Unit Price',
       'Unit Cost', 'Latitude', 'Longitude', 'Target'],
      dtype='str')

In [89]:
import plotly.express as px

division_units = (
    df.groupby("Division", as_index=False)["Units"]
      .sum()
)

fig = px.bar(
    division_units,
    x="Division",
    y="Units",
    title="Total Units by Division"
)

fig.update_layout(
    width=1000,
    height=600
)

fig.show()

In [90]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

df["Ship Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

df["Ship Days"].sort_values(ascending=False).head()

5049    2011
5050    2011
167     2008
166     2008
7390    2007
Name: Ship Days, dtype: int64

In [92]:
df["Ship Days"].value_counts()

Ship Days
2004    2837
2005    2235
2002    1361
2006    1204
2003    1025
2007     630
2000     523
2001     369
2008       2
2011       2
Name: count, dtype: int64