In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mlp

In [2]:
df_factory = pd.read_csv("C:/Users/Mohan/Documents/Candy/data/version_0/Candy_Factories.csv")

In [3]:
df_factory.head()

             Factory   Latitude   Longitude
0      Lot's O' Nuts  32.881893 -111.768036
1    Wicked Choccy's  32.076176  -81.088371
2        Sugar Shack  48.119140  -96.181150
3     Secret Factory  41.446333  -90.565487
4  The Other Factory  35.117500  -89.971107

In [4]:
df_factory.shape

(5, 3)

In [5]:
df_factory.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Factory    5 non-null      str
 1   Latitude   5 non-null      float64
 2   Longitude  5 non-null      float64
dtypes: float64(2), str(1)
memory usage: 252.0 bytes

In [6]:
df_factory.describe()

        Latitude   Longitude
count   5.000000    5.000000
mean   37.928208  -93.914830
std     6.779453   11.348593
min    32.076176 -111.768036
25%    32.881893  -96.181150
50%    35.117500  -90.565487
75%    41.446333  -89.971107
max    48.119140  -81.088371

In [7]:
df_factory.isnull().sum()

Factory      0
Latitude     0
Longitude    0
dtype: int64

In [8]:
df_factory.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [9]:

# Save CSV
df_factory.to_csv("C:/Users/Mohan/Documents/Candy/data/version_1/Candy_Factories.csv", index=False)