In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_uszips = pd.read_csv("C:/Users/Mohan/Documents/Candy/data/version_0/zips.csv")

In [3]:
df_uszips.head()

,zip,lat,lng,city,state_id,state_name,zcta,parent_zcta,population,density,county_fips,county_name,county_weights,county_names_all,county_fips_all,imprecise,military,timezone
0,601,18.18027,-66.75266,Adjuntas,PR,Puerto Rico,True,NaN,16834.0,100.9,72001,Adjuntas,"{""72001"": 98.74, ""72141"": 1.26}",Adjuntas|Utuado,72001|72141,False,False,America/Puerto_Rico
1,602,18.36075,-67.17541,Aguada,PR,Puerto Rico,True,NaN,37642.0,479.2,72003,Aguada,"{""72003"": 100}",Aguada,72003,False,False,America/Puerto_Rico
2,603,18.45744,-67.12225,Aguadilla,PR,Puerto Rico,True,NaN,49075.0,551.7,72005,Aguadilla,"{""72005"": 99.76, ""72099"": 0.24}",Aguadilla|Moca,72005|72099,False,False,America/Puerto_Rico
3,606,18.16585,-66.93716,Maricao,PR,Puerto Rico,True,NaN,5590.0,48.7,72093,Maricao,"{""72093"": 82.27, ""72153"": 11.66, ""72121"": 6.06}",Maricao|Yauco|Sabana Grande,72093|72153|72121,False,False,America/Puerto_Rico
4,610,18.29110,-67.12243,Anasco,PR,Puerto Rico,True,NaN,25542.0,265.7,72011,Añasco,"{""72011"": 96.71, ""72099"": 2.82, ""72083"": 0.37,...",Añasco|Moca|Las Marías|Aguada,72011|72099|72083|72003,False,False,America/Puerto_Rico

In [4]:
df_uszips.shape

(33787, 18)

In [5]:
df_uszips.info()

<class 'pandas.DataFrame'>
RangeIndex: 33787 entries, 0 to 33786
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   zip               33787 non-null  int64
 1   lat               33787 non-null  float64
 2   lng               33787 non-null  float64
 3   city              33787 non-null  str
 4   state_id          33787 non-null  str
 5   state_name        33787 non-null  str
 6   zcta              33787 non-null  bool
 7   parent_zcta       0 non-null      float64
 8   population        33770 non-null  float64
 9   density           33770 non-null  float64
 10  county_fips       33787 non-null  int64
 11  county_name       33787 non-null  str
 12  county_weights    33787 non-null  str
 13  county_names_all  33787 non-null  str
 14  county_fips_all   33787 non-null  str
 15  imprecise         33787 non-null  bool
 16  military          33787 non-null  bool
 17  timezone          33787 non-null  str
dtypes: bool(3), float64(5), int64(2), str(8)
memory usage: 4.0 MB

In [6]:
df_uszips.describe()

,zip,lat,lng,parent_zcta,population,density,county_fips
count,33787.000000,33787.000000,33787.000000,0.0,33770.000000,33770.000000,33787.000000
mean,49705.528221,38.800843,-90.956464,NaN,9901.170092,510.054519,29989.620446
std,27559.058327,5.387652,15.666437,NaN,14908.642037,1944.753885,15504.744997
min,601.000000,-14.219840,-176.629620,NaN,0.000000,0.000000,1001.000000
25%,26724.000000,35.363910,-97.226565,NaN,650.000000,7.300000,18057.000000
50%,49725.000000,39.476220,-88.184120,NaN,2657.000000,30.650000,30031.000000
75%,72171.500000,42.103845,-80.237865,NaN,13329.000000,268.775000,42055.000000
max,99929.000000,71.274340,145.753490,NaN,134008.000000,60879.200000,78030.000000

In [7]:
df_uszips.isnull().sum()

zip                     0
lat                     0
lng                     0
city                    0
state_id                0
state_name              0
zcta                    0
parent_zcta         33787
population             17
density                17
county_fips             0
county_name             0
county_weights          0
county_names_all        0
county_fips_all         0
imprecise               0
military                0
timezone                0
dtype: int64

In [8]:
df_uszips["population"]=df_uszips["population"].interpolate()
df_uszips["density"]=df_uszips["density"].interpolate()

In [9]:
df_uszips.isnull().sum()

zip                     0
lat                     0
lng                     0
city                    0
state_id                0
state_name              0
zcta                    0
parent_zcta         33787
population              0
density                 0
county_fips             0
county_name             0
county_weights          0
county_names_all        0
county_fips_all         0
imprecise               0
military                0
timezone                0
dtype: int64

In [10]:
df_uszips.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
33782    False
33783    False
33784    False
33785    False
33786    False
Length: 33787, dtype: bool

In [11]:
df_uszips=df_uszips.drop(columns=['parent_zcta'])

In [12]:
df_uszips.duplicated().unique()

array([False])

In [13]:
df_uszips.info()

<class 'pandas.DataFrame'>
RangeIndex: 33787 entries, 0 to 33786
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   zip               33787 non-null  int64
 1   lat               33787 non-null  float64
 2   lng               33787 non-null  float64
 3   city              33787 non-null  str
 4   state_id          33787 non-null  str
 5   state_name        33787 non-null  str
 6   zcta              33787 non-null  bool
 7   population        33787 non-null  float64
 8   density           33787 non-null  float64
 9   county_fips       33787 non-null  int64
 10  county_name       33787 non-null  str
 11  county_weights    33787 non-null  str
 12  county_names_all  33787 non-null  str
 13  county_fips_all   33787 non-null  str
 14  imprecise         33787 non-null  bool
 15  military          33787 non-null  bool
 16  timezone          33787 non-null  str
dtypes: bool(3), float64(4), int64(2), str(8)
memory usage: 3.7 MB

In [14]:
df_uszips[['tz_region', 'tz_city']] = df_uszips['timezone'].str.split('/', n=1, expand=True)

In [18]:
df_uszips=df_uszips.drop(columns=["county_weights","county_names_all","county_fips_all","imprecise","military"])

In [19]:
# Save CSV
df_uszips.to_csv("C:/Users/Mohan/Documents/Candy/data/version_1/zips.csv", index=False)